### ISSUE TITLE
Fireworks only going few inches up

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/Fireworks#2]
Place a firework to the ground, it will only go up by few and not fly high up

**Comment by Muqsit** [comment]
Please send a recording, it seems to be working perfectly.

**Comment by ghost** [comment]
There's a "Flight Duration: 1" in the name of the firework. Maybe that duration is the cause?

**Comment by ghost** [comment]
https://youtu.be/A858xhZVZkc
