### ISSUE TITLE
API to launch a firework from a plugin

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/Fireworks#3]
Is there a way to launch a firework using this from my plugin?

**Comment by Muqsit** [comment]
Launching, not really. You can create a Fireworks like this:
```php
$firework = Item::get(Item::FIREWORKS);
$firework->addExplosion(Fireworks::TYPE_CREEPER_HEAD, Fireworks::COLOR_RED);
$firework->addExplosion(Fireworks::TYPE_HUGE_SPHERE, Fireworks::COLOR_RED);
$firework->setFlightDuration(3);
```
Then create the FireworkRocket
```php
/** @var Vector3 $pos */
/** @var Level $level */

$nbt = Entity::createBaseNBT($pos, new Vector3(0.001, 0.05, 0.001), lcg_value() * 360, 90);

$entity = Entity::createEntity("FireworksRocket", $level, $nbt, $firework);

$entity->spawnToAll();
```

**Comment by ghost** [comment]
@Muqsit [21:49:31] [Server thread/CRITICAL]: Could not tick level "world": Undefined property: stdClass::$z
[21:49:31] [Server thread/CRITICAL]: ErrorException: "Undefined property: stdClass::$z" (EXCEPTION) in "Fireworks-master/src/BlockHorizons/Fireworks/entity/FireworksRocket" at line 41

**Comment by ghost** [comment]
The fireworks worked though

**Comment by Muqsit** [comment]
@captainleviftw are you calling close() on the entity?

**Comment by Muqsit** [comment]
it's caused when the entity tries to move while being closed https://twitter.com/dktapps/status/1004690888898088960?s=19
